---
http:
  routers:
    leaders:
      entrypoints:
        - websecure
      rule: Host(`leaders.hpclab.ru`)
      service: leaders2023

  services:
    leaders2023:
      loadBalancer:
        servers:
          - url: http://10.50.50.34:3000
