version: '3'

services:
  db:
    image: postgis/postgis:15-3.3-alpine
    environment:
      POSTGRES_DB: leaders2023
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db:
