version: "3"

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    network_mode: host
    command: "--configFile /config/static.yaml"
    environment:
      REGRU_USERNAME: ${REGRU_USERNAME}
      REGRU_PASSWORD: ${REGRU_PASSWORD}
    volumes:
      - ./config:/config:ro
      - /etc/localtime:/etc/localtime:ro
      - letsencrypt:/letsencrypt
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

volumes:
  letsencrypt:
