version: "3"

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    network_mode: host
    command: "--configFile /config/static.yaml"
    volumes:
      - ./config:/config:ro
      - /etc/localtime:/etc/localtime:ro
      - letsencrypt:/letsencrypt
    restart: unless-stopped

volumes:
  letsencrypt:
